# Generated by Django 3.2.5 on 2021-09-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of article, blog entry, etc.', max_length=100)),
                ('body', models.TextField()),
                ('private', models.BooleanField(default=True, help_text='Private requires authenticated user (any) to see. If this is False, anyone can see it.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Owner of snippet. Generally the author.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
