# Generated by Django 3.2.5 on 2021-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of article, blog entry, etc.', max_length=100)),
                ('body', models.TextField()),
                ('owner', models.CharField(help_text='Owner of snippet. Generally the author.', max_length=20)),
                ('private', models.BooleanField(default=True, help_text='Private requires authenticated user (any) to see. If this is False, anyone can see it.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
