# Generated by Django 3.2.5 on 2021-09-21 21:49

from django.db import migrations, models
import snippets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jti',
            field=models.CharField(default=snippets.utils.generate_jti, editable=False, help_text='JWT tokens for the user get revoked when JWT id has regenerated.', max_length=64, verbose_name='jwt id'),
        ),
    ]
